StoreApp/SMVC/Controllers/LoginController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SBL;
using SModels;
using SMVC.Models;
using System.Collections.Generic;
using System.Text.Json;

namespace SMVC.Controllers
{
    public class LoginController : Controller
    {
        private IStoreBL _storeBL;
        private IMapper _mapper;
        private Customer _customer;
        private readonly ILogger<LoginController> _logger;

        public LoginController(IStoreBL store, IMapper mapper, ILogger<LoginController> logger)
        {
            _storeBL = store;
            _mapper = mapper;
            _logger = logger;
        }

        // GET: LoginController
        public ActionResult Index()
        {
            return View("../Home/Index");
        }

        public ActionResult Logout()
        {
            return View();
        }
        public ActionResult UserSettings()
        {
            return View();
        }
        public ActionResult UserInformation()
        {
            return View();
        }
        public ActionResult OrderHistory()
        {
            _customer = JsonSerializer.Deserialize<Customer>(HttpContext.Session.GetString("userData"));
            List<Orders> orders = _storeBL.getOrderHistory(_customer);
            return View(orders);
        }
        public ActionResult OrderDetails(int id)
        {
            Orders order = _storeBL.getOrderByID(id);
            List<OrderItem> cartItems = _storeBL.getOrderDetails(order);
            ViewBag.order = order;
            ViewBag.products = _storeBL.getAllProducts();
            return View(cartItems);
        }
        public ActionResult LocationHistory()
        {
            _customer = JsonSerializer.Deserialize<Customer>(HttpContext.Session.GetString("userData"));
            List<Store> storesVisited = _storeBL.getLocationHistory(_customer);
            ViewBag.Store = storesVisited;
            return View(storesVisited);
        }
        public ActionResult GetCustomerByName()
        {
            return View();
        }
        // GET: LoginController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: LoginController/Create
        public ActionResult Create()
        {
            
            return View();
        }

        // POST: LoginController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(LoginCreateVM customer)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    _logger.LogInformation("User is logged in");
                    _customer = _storeBL.getCustomerByEmail(_mapper.cast2Customer(customer).Email);
                    HttpContext.Session.SetString("userData", JsonSerializer.Serialize(_customer));
                    return RedirectToAction(nameof(Index));
                }
                catch
                {
                    return View();
                }
            }

            return View();
        }

        // GET: LoginController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: LoginController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: LoginController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: LoginController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

StoreApp/SMVC/Controllers/StoreController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using SBL;
using SModels;
using SMVC.Models;
using System.Collections.Generic;
using System.Text.Json;

namespace SMVC.Controllers
{
    public class StoreController : Controller
    {
        private IStoreBL _storeBL;
        private IMapper _mapper;
        private Customer _customer;
        private Store _store;
        private Product _product;
        private Orders _order;

        public StoreController(IStoreBL storeBL, IMapper mapper)
        {
            _storeBL = storeBL;
            _mapper = mapper;
        }

        // GET: StoreController
        public ActionResult Index()
        {
            return View(_storeBL.getAllStores());
        }

        public ActionResult SuccessfulPurchase()
        {
            Orders order = _storeBL.addNewOrder();
            HttpContext.Session.SetString("orderData", JsonSerializer.Serialize(order));
            return View();
        }

        // GET: StoreController/Details/StoreName={storename}
        public ActionResult Details(string StoreName)
        {
            _store = _storeBL.getStoreByName(StoreName);
            ViewBag.Store = _store;
            if (HttpContext.Session.GetString("userData") != null)
            {
                _customer = JsonSerializer.Deserialize<Customer>(HttpContext.Session.GetString("userData"));
                LocationVisited store = new LocationVisited();
                store.CustomerID = _customer.ID;
                store.StoreID = _store.ID;
                _storeBL.addVisistedStore(store);
            }
            ViewBag.storeInventories = _storeBL.getStoreInventory(_store);
            ViewBag.products = _storeBL.getAllProducts();
            return View(_store);
        }

        // GET: StoreController/Create
        public ActionResult Create()
        {
            return View();
        }
        public ActionResult OrderHistoryOfLocation(int id)
        {
            Store store = _storeBL.getStoreByID(id);
            List<Orders> orders = _storeBL.getOrderHistory(store);
            return View(orders);
        }
        public ActionResult CreateStoreInventory(int id)
        {
            ViewBag.products = _storeBL.getAllProducts();
            ViewBag.StoreID = id;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateStoreInventory(StoreInventoryVM inventoryVM)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    if (_storeBL.inventoryExists(inventoryVM.ProductID, inventoryVM.StoreID))
                    {
                        _product = _storeBL.getProductByID(inventoryVM.ProductID);
                        _store = _storeBL.getStoreByID(inventoryVM.StoreID);
                        int storeItemQuantity = _storeBL.getInventoryQuantity(_product, _store);
                        StoreInventory storeInventory = _storeBL.getInventoryItem(_product, _store);
                        storeInventory.InventoryQuantity = storeItemQuantity + inventoryVM.InventoryQuantity;
                        _storeBL.updateStoreInventory(storeInventory);
                    }
                    else
                    {
                        _storeBL.addProductToInventory(_mapper.cast2StoreInventory(inventoryVM));
                    }

                    return RedirectToAction(nameof(Index));
                }
                catch
                {
                    return View();
                }
            }
            return View();
        }

        public ActionResult AddQuantityToCart(int storeid, int prodId)
        {
            StoreInventoryVM storeInventoryVM = new StoreInventoryVM();
            storeInventoryVM.StoreID = storeid;
            storeInventoryVM.ProductID = prodId;
            return View(storeInventoryVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddQuantityToCart(StoreInventoryVM inventoryVM)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    _product = _storeBL.getProductByID(inventoryVM.ProductID);
                    _order = JsonSerializer.Deserialize<Orders>(HttpContext.Session.GetString("orderData"));
                    _store = _storeBL.getStoreByID(inventoryVM.StoreID);

                    OrderItem newOrderItem = new OrderItem();
                    newOrderItem.ProductID = inventoryVM.ProductID;
                    newOrderItem.ProductQuantity = inventoryVM.InventoryQuantity;
                    newOrderItem = _storeBL.addOrderItem(newOrderItem);

                    _order.OrderTotal += _product.Price * newOrderItem.ProductQuantity;
                    HttpContext.Session.SetString("orderData", JsonSerializer.Serialize(_order));

                    if (HttpContext.Session.GetString("userData") != null)
                    {
                        TrackOrder track = new TrackOrder();
                        _customer = JsonSerializer.Deserialize<Customer>(HttpContext.Session.GetString("userData"));
                        track.CustomerID = _customer.ID;
                        track.OrderID = _order.ID;
                        track.OrderItemID = newOrderItem.ID;
                        track.StoreID = inventoryVM.StoreID;
                        _storeBL.addTrackOrderItem(track);
                    }
                    else
                    {
                        TrackOrder track = new TrackOrder();
                        track.CustomerID = 8;
                        track.OrderID = _order.ID;
                        track.OrderItemID = newOrderItem.ID;
                        track.StoreID = inventoryVM.StoreID;
                        _storeBL.addTrackOrderItem(track);
                    }
                    int storeItemQuantity = _storeBL.getInventoryQuantity(_product, _store);
                    StoreInventory storeInventory = _storeBL.getInventoryItem(_product, _store);
                    storeInventory.InventoryQuantity = storeItemQuantity - inventoryVM.InventoryQuantity;
                    _storeBL.updateStoreInventory(storeInventory);
                    return RedirectToAction(nameof(Index));
                }
                catch
                {
                    return View();
                }
            }
            return View();
        }

        public ActionResult Cart()
        {
            _order = JsonSerializer.Deserialize<Orders>(HttpContext.Session.GetString("orderData"));
            List<OrderItem> cartItems = _storeBL.getOrderDetails(_order);
            ViewBag.products = _storeBL.getAllProducts();
            return View(cartItems);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Cart(OrderItem orderItem)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    Orders order = JsonSerializer.Deserialize<Orders>(HttpContext.Session.GetString("orderData"));
                    _storeBL.updateOrderTotal(order);
                    return RedirectToAction(nameof(SuccessfulPurchase));
                }
                catch
                {
                    return View();
                }
            }
            return View();
        }

        // POST: StoreController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: StoreController/Edit/5
        public ActionResult Edit(int id)
        {
            ViewBag.products = _storeBL.getAllProducts();
            return View(_storeBL.getStoreByID(id));
        }

        // POST: StoreController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(StoreInventory inventory)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: StoreController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: StoreController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

StoreApp/SMVC/Views/Store/AddQuantityToCart.cshtml
@model SMVC.Models.StoreInventoryVM

@{
    ViewData["Title"] = "AddQuantityToCart";
}

<h1>Add To Cart</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AddQuantityToCart">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="InventoryQuantity" class="control-label"></label>
                <input asp-for="InventoryQuantity" class="form-control" />
                <span asp-validation-for="InventoryQuantity" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="StoreID" value=@Model.StoreID />
            <input type="hidden" asp-for="ProductID" value=@Model.ProductID />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

StoreApp/SMVC/Views/Store/Cart.cshtml
@using SModels;
@using System.Text.Json;
@using Microsoft.AspNetCore.Http;
@model IEnumerable<SModels.OrderItem>

@{
    ViewData["Title"] = "Cart";
    List<Product> products = ViewBag.products;
    Orders order = JsonSerializer.Deserialize<Orders>(Context.Session.GetString("orderData"));
}

<h1 class="text-white-50 text-center">Cart</h1>

<table class="table">
    <thead>
        <tr>
            <th class="text-white-50">
                Product Name:
            </th>
            <th class="text-white-50">
                Price:
            </th>
            <th class="text-white-50">
                Quantity:
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var inv in Model)
        {
            @foreach (var prod in products)
            {
                @if (inv.ProductID == prod.ID)
                {
                    <tr>
                        <td class="col-md-5 text-white-50">
                            @prod.ProductName
                        </td>
                        <td class="col-md-3 text-white-50">
                            @prod.Price
                        </td>
                        <td class="col-md-2 text-white-50">
                            @inv.ProductQuantity
                        </td>
                    </tr>
                }
            }
        }
    </tbody>
</table>
<div>
    <dl class="row">
        <dt class="col-sm-2 text-white-50">
            Order Total:
        </dt>
        <dd class="col-sm-10 text-white-50">
            @order.OrderTotal
        </dd>
    </dl>
</div>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Cart">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <input type="submit" value="Purchase" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

StoreApp/SMVC/Views/Store/CreateStoreInventory.cshtml
@using SModels;
@using System.Collections.Generic;

@model SMVC.Models.StoreInventoryVM

@{
    ViewData["Title"] = "Edit";
    List<Product> products = ViewBag.products;
    int id = ViewBag.StoreID;
}

<h3 class="text-center text-white-50">Edit Store Inventory</h3>
<h8 class="text-center text-white-50">The quantity adds to the product</h8>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateStoreInventory">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ProductID" class="control-label text-white-50"></label>
                <input asp-for="ProductID" class="form-control" />
                <span asp-validation-for="ProductID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="InventoryQuantity" class="control-label text-white-50"></label>
                <input asp-for="InventoryQuantity" class="form-control" />
                <span asp-validation-for="InventoryQuantity" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="StoreID" value=@id />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<h4 class="text-center text-white-50">Choose from the list below</h4>

<table class="table">
    <thead>
        <tr>
            <th class="text-white-50">
                Name:
            </th>
            <th class="text-white-50">
                ID:
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var prod in products)
        {
            <tr>
                <td class="text-white-50">
                    @prod.ProductName
                </td>
                <td class="text-white-50">
                    @prod.ID
                </td>
            </tr>
        }
    </tbody>
</table>

StoreApp/SMVC/Views/Store/Details.cshtml
@using SModels;
@using System.Text.Json;
@using Microsoft.AspNetCore.Http;
@model SModels.Store


@{
    ViewData["Title"] = "Details";
    List<StoreInventory> storeInventories = ViewBag.storeInventories;
    List<Product> products = ViewBag.products;
    Store store = ViewBag.Store;
    Customer customer;
    if (Context.Session.GetString("userData") == null)
    {
        customer = null;
    }
    else
    {
        customer = JsonSerializer.Deserialize<Customer>(Context.Session.GetString("userData"));
    }
}

<div>
    <h3 class="text-center text-white">@Model.StoreName</h3>
    <hr />
    <dl class="row">
        <dt class="col-sm-2 text-white-50">
            Store Location:
        </dt>
        <dd class="col-sm-10 text-white-50">
            @Model.StoreLocation
        </dd>
    </dl>
</div>

<table class="table">
    <thead>
        <tr>
            <th class="col-md-5 text-white-50">
                Name:
            </th>
            <th class="col-md-3 text-white-50">
                Price:
            </th>
            <th class="col-md-2 text-white-50">
                Quantity:
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var inv in storeInventories)
        {
            @foreach (var prod in products)
            {
                @if (inv.ProductID == prod.ID)
                {
                    @if (inv.InventoryQuantity > 0)
                    {
                        <tr>
                            <td class="col-md-3 text-white-50">
                                @prod.ProductName
                            </td>
                            <td class="col-md-3 text-white-50">
                                @prod.Price
                            </td>
                            <td class="col-md-2 text-white-50">
                                @inv.InventoryQuantity
                            </td>
                            <td class="col-md-4 text-white-50">
                                @Html.ActionLink("Add to Cart", "AddQuantityToCart", "Store", new { storeid = store.ID, prodId = inv.ProductID })
                            </td>
                        </tr>
                    }
                }
            }
        }
    </tbody>
</table>

@if (customer != null)
{
    @if (customer.IsManager)
    {
        <div>
            @Html.ActionLink("Add Products", "CreateStoreInventory", "Store", new { id = Model.ID })
        </div>
        <div>
            @Html.ActionLink("Order History", "OrderHistoryOfLocation", "Store", new { id = Model.ID })
        </div>
    }
}

StoreApp/SMVC/Views/Store/Index.cshtml
@model IEnumerable<SModels.Store>

@{
    ViewData["Title"] = "Index";
}

<h1 class="text-center text-white">All Stores</h1>

<table class="table">
    <thead>
        <tr>
            <th class="text-white-50">
                @Html.DisplayNameFor(model => model.StoreName)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.ActionLink(item.StoreName, "Details", "Store", new { item.StoreName })
            </td>
        </tr>
}
    </tbody>
</table>

StoreApp/SMVC/Views/Store/OrderHistoryOfLocation.cshtml
@model IEnumerable<SModels.Orders>

@{
    ViewData["Title"] = "OrderHistory";
    int count = 1;
}

<h1 class="text-white text-center">Order History</h1>

<table class="table">
    <thead class="text-white-50">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.OrderDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.OrderTotal)
            </th>
        </tr>
    </thead>
    <tbody class="text-white-50">
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @count
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.OrderDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.OrderTotal)
                </td>
                <td>
                    @Html.ActionLink("Details", "OrderDetails", "Login", new { id = item.ID })
                </td>
            </tr>
            count++;
        }
    </tbody>
</table>

StoreApp/SMVC/Views/Store/SuccessfulPurchase.cshtml
@{
    ViewData["Title"] = "SuccessfulPurchase";
}

<h1 class="text-white">Successful Purchase</h1>